### ISSUE TITLE
Web push notifications

### ISSUE THREAD

**Issue by notlmn** [GoogleChromeLabs/devwebfeed#10]
Any ideas of adding web push notifications?

**Comment by ebidel** [comment]
Not opposed, just haven't found the time :) Let me know if you're interested in helping out with that.

**Comment by notlmn** [comment]
Never setup a push server before but will try to.

**Comment by ebidel** [comment]
Oh that's ok then. There's actually a fair amount of work. That's why I'm
avoiding adding it :)

**Comment by PaulKinlan** [comment]
I've got a third party push server I made that I would be happy to spruce up

**Comment by notlmn** [comment]
@paulkinlan I'd love to see how that would work.

The reason I haven't tried to setup a push server is I couldn't get GCP to get me an analytics service account key, tried enabling and disabling all kinds of services that GCP provides but it still throws some random error at the end everytime.
